language: elixir

elixir:
  - 1.2.3

otp_release:
  - 18.2.1

env: MIX_ENV=test

sudo: false # faster builds

notifications:
  email: false

script:
  - mix compile --warnings-as-errors
  - mix test
  # - mix dogma

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
