language: elixir

elixir:
  - 1.0.4

otp_release:
  - 17.4

env: MIX_ENV=test

sudo: false # faster builds

notifications:
  email: false

script:
  - mix test
  - mix dogma

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
